services:
  - type: web
    name: house-price-backend
    runtime: python
    startCommand: "pip install -r requirements.txt && uvicorn app:app --host 0.0.0.0 --port 8001"
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
